---
- hosts: localhost
  become: yes
  tasks: 
   - name: creating ec2 instance using dynamiv inventroy 
     ec2:
      key_name: ansiblenode
      image: ami-0d2ccfcf1dfc7c179
      instance_type: t2.micro
      wait: yes
      region: us-east-1
      group: launch-wizard-16
      count: 1
      vpc_subnet_id: subnet-0a2a9324
      assign_public_ip: yes
      instance_tags:
        Name: ansibleec2node
