---
- hosts: all
  become: yes
  tasks:
   - name: creating a loop installation one by one
     apt:
       name: "{{ item }}"
       state: present
     with_items:
       - git
       - tree
       - wget
