---
# tasks file for mytomrole  
- name: install tomcat
  yum:
   name: tomcat
   state: present

- name: copying conf file using jinja templates to all nodes
  template:
     src: templates/tomconfcreat.j2
     dest: /usr/share/tomcat/conf/tomcat.conf
  notify: starttomcat

- name: to Install Admin Packages
  yum:
   name: "{{ item }}"
   state: present
  with_items:
     - tomcat-webapps
     - tomcat-admin-webapps 

- name: copying tomcat user.xml from jinja templates to all nodes
  template:
     src: templates/tomuserxml.j2
     dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restarttomcat

- name: deploy maha java war file into all nodes 
  get_url: 
    url: https://s3.amazonaws.com/maha4iac/mahaLogin.war
    dest: /usr/share/tomcat/webapps/mahaLogin.war
  notify: restarttomcat
